"""add gotify support

Revision ID: 0fa71b2e5d30
Revises: bc237f8b139d
Create Date: 2025-04-24 14:27:10.412771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fa71b2e5d30"
down_revision: Union[str, None] = "bc237f8b139d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "service",
                sa.Enum("apprise", "gotify", name="notificationserviceenum"),
                nullable=False,
                server_default="apprise",
            )
        )
        batch_op.alter_column("apprise_url", new_column_name="url")

    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column(
            "service",
            server_default=None,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.alter_column("url", new_column_name="apprise_url")
        batch_op.drop_column("service")

    # ### end Alembic commands ###
