"""add additional fields

Revision ID: 304eed96f8ed
Revises: 0fa71b2e5d30
Create Date: 2025-04-24 15:29:26.686894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "304eed96f8ed"
down_revision: Union[str, None] = "0fa71b2e5d30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "additional_fields", sa.JSON(), nullable=True, server_default="{}"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("additional_fields")

    # ### end Alembic commands ###
