"""rename prowlarr date col

Revision ID: 6477fe89a011
Revises: 9a71f7625ec9
Create Date: 2025-02-16 16:50:35.801378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6477fe89a011'
down_revision: Union[str, None] = '9a71f7625ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prowlarrsource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('publishDate')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prowlarrsource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publishDate', sa.DATETIME(), nullable=False))
        batch_op.drop_column('publish_date')

    # ### end Alembic commands ###
