"""add search_attempts next_search_at downloaded_file to bookrequest

Revision ID: 6d620131023f
Revises: 63489e50e337
Create Date: 2026-02-24 20:09:50.328921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d620131023f'
down_revision: Union[str, None] = '63489e50e337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('next_search_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('downloaded_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookrequest', schema=None) as batch_op:
        batch_op.drop_column('downloaded_file')
        batch_op.drop_column('next_search_at')
        batch_op.drop_column('search_attempts')

    # ### end Alembic commands ###
