"""manual requests downloaded flag

Revision ID: 873737d287d3
Revises: 76d7ccb8a116
Create Date: 2025-03-16 09:39:19.684439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "873737d287d3"
down_revision: Union[str, None] = "76d7ccb8a116"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manualbookrequest", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "downloaded",
                sa.Boolean(),
                nullable=False,
                server_default="false",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("manualbookrequest", schema=None) as batch_op:
        batch_op.drop_column("downloaded")

    # ### end Alembic commands ###
