"""add root user attribute

Revision ID: 8ebcc63e79ea
Revises: e4f418be2275
Create Date: 2025-02-18 12:27:50.522079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ebcc63e79ea"
down_revision: Union[str, None] = "e4f418be2275"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("root", sa.Boolean(), nullable=False, server_default="false")
        )
    op.execute("UPDATE user SET root = true WHERE \"group\" = 'admin'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("root")

    # ### end Alembic commands ###
