"""add notifications

Revision ID: 9f0430047af4
Revises: e6fa1af6d802
Create Date: 2025-02-18 15:37:27.614750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f0430047af4'
down_revision: Union[str, None] = 'e6fa1af6d802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apprise_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('event', sa.Enum('on_new_request', name='eventenum'), nullable=False),
    sa.Column('title_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_template', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
