"""simplify BookRequests

Revision ID: cafe562e2832
Revises: 787e0b375062
Create Date: 2025-02-16 13:22:22.576727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cafe562e2832'
down_revision: Union[str, None] = '787e0b375062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookrequest', schema=None) as batch_op:
        batch_op.drop_column('cover_image')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('authors')
        batch_op.drop_column('narrators')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('narrators', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('authors', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
