"""add downloaded attribute

Revision ID: e6fa1af6d802
Revises: 8ebcc63e79ea
Create Date: 2025-02-18 13:32:08.137756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6fa1af6d802"
down_revision: Union[str, None] = "8ebcc63e79ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookrequest", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "downloaded", sa.Boolean(), nullable=False, server_default="false"
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bookrequest", schema=None) as batch_op:
        batch_op.drop_column("downloaded")

    # ### end Alembic commands ###
